In [1]:
from sqlalchemy import create_engine, text

In [ ]:
engine = create_engine(
    "mysql+pymysql://root:ubmVuVNFzorFXnnexAwbdWqTdKnuTwcb@sakura.proxy.rlwy.net:29766/railway"
)

print("✅ Connected Successfully")

✅ Connected Successfully

In [3]:
from sqlalchemy import text

with engine.begin() as conn:
    conn.execute(text("""
        CREATE TABLE IF NOT EXISTS users (
            user_id INT AUTO_INCREMENT PRIMARY KEY,
            full_name VARCHAR(100) NOT NULL,
            email VARCHAR(100) UNIQUE NOT NULL,
            phone VARCHAR(15),
            password VARCHAR(255) NOT NULL,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        );
    """))

print("✅ Users table created successfully!")

✅ Users table created successfully!

In [4]:
from sqlalchemy import text

with engine.begin() as conn:
    conn.execute(text("""
        CREATE TABLE IF NOT EXISTS favorites (
            favorite_id INT AUTO_INCREMENT PRIMARY KEY,
            user_id INT NOT NULL,
            isbn VARCHAR(20) NOT NULL,
            added_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

            FOREIGN KEY (user_id) REFERENCES users(user_id),
            FOREIGN KEY (isbn) REFERENCES books(isbn)
        );
    """))

print("✅ Favorites table created successfully!")

✅ Favorites table created successfully!

In [5]:
from sqlalchemy import text

with engine.begin() as conn:
    conn.execute(text("""
        CREATE TABLE IF NOT EXISTS orders (
            order_id INT AUTO_INCREMENT PRIMARY KEY,
            user_id INT NOT NULL,
            isbn VARCHAR(20) NOT NULL,
            customer_name VARCHAR(100) NOT NULL,
            phone VARCHAR(15) NOT NULL,
            address TEXT NOT NULL,
            quantity INT DEFAULT 1,
            order_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            status VARCHAR(30) DEFAULT 'Pending',

            FOREIGN KEY (user_id) REFERENCES users(user_id),
            FOREIGN KEY (isbn) REFERENCES books(isbn)
        );
    """))

print("✅ Orders table created successfully!")

✅ Orders table created successfully!

In [ ]:
from sqlalchemy import create_engine, text

engine = create_engine(
   "mysql+pymysql://root:ubmVuVNFzorFXnnexAwbdWqTdKnuTwcb@sakura.proxy.rlwy.net:29766/railway"
)

In [3]:
with engine.begin() as conn:

    conn.execute(text("""

    CREATE TABLE IF NOT EXISTS users(

        id INT AUTO_INCREMENT PRIMARY KEY,

        full_name VARCHAR(100),

        email VARCHAR(100) UNIQUE,

        phone VARCHAR(20),

        password VARCHAR(255)

    )

    """))

print("Users table created successfully.")

Users table created successfully.

In [4]:
df = pd.read_sql("SELECT * FROM users", engine)
print(df)

NameError: name 'pd' is not defined

In [ ]:
import pandas as pd
from sqlalchemy import create_engine

engine = create_engine(
    "mysql+pymysql://root:ubmVuVNFzorFXnnexAwbdWqTdKnuTwcb@sakura.proxy.rlwy.net:29766/railway"
)

In [6]:
df = pd.read_sql("SELECT * FROM users", engine)
df

Empty DataFrame
Columns: [user_id, full_name, email, phone, password, created_at]
Index: []

In [ ]:
import pandas as pd
from sqlalchemy import create_engine

engine = create_engine(
    "mysql+pymysql://root:ubmVuVNFzorFXnnexAwbdWqTdKnuTwcb@sakura.proxy.rlwy.net:29766/railway"
)

df = pd.read_sql("SELECT * FROM users", engine)

print(df)

In [ ]:
import pandas as pd
from sqlalchemy import create_engine

engine = create_engine(
    "mysql+pymysql://root:ubmVuVNFzorFXnnexAwbdWqTdKnuTwcb@sakura.proxy.rlwy.net:29766/railway"
)

df = pd.read_sql("SELECT * FROM users", engine)
print(df)

   user_id        full_name                  email       phone   password  \
0        1  vaishnavi barve  vaishnavi25@gmail.com  1234567890  admin@123

           created_at
0 2026-07-10 20:31:28

In [3]:
import pandas as pd

df = pd.read_sql("SELECT * FROM books LIMIT 5", engine)

print(df.columns)

Index(['book_id', 'isbn', 'title', 'author', 'publication_year', 'publisher',
       'image_url'],
      dtype='str')

In [4]:
from sqlalchemy import text

with engine.begin() as conn:
    conn.execute(text("""
        ALTER TABLE books
        ADD COLUMN category VARCHAR(50)
    """))

print("Category column added successfully!")

Category column added successfully!

In [5]:
import random
import pandas as pd

categories = [
    "Fiction",
    "Education",
    "Horror",
    "Romance",
    "Science",
    "Children"
]

df = pd.read_sql("SELECT book_id FROM books", engine)

with engine.begin() as conn:
    for book_id in df["book_id"]:
        conn.execute(
            text("""
                UPDATE books
                SET category=:category
                WHERE book_id=:book_id
            """),
            {
                "category": random.choice(categories),
                "book_id": int(book_id)
            }
        )

print("Categories added successfully!")

Categories added successfully!

In [6]:
df = pd.read_sql(
    "SELECT title, category FROM books LIMIT 10",
    engine
)

print(df)

                                               title   category
0                                Classical Mythology    Romance
1                                       Clara Callan    Fiction
2                               Decision in Normandy   Children
3  Flu: The Story of the Great Influenza Pandemic...    Science
4                             The Mummies of Urumchi    Fiction
5                             The Kitchen God's Wife  Education
6  What If?: The World's Foremost Military Histor...  Education
7                                    PLEADING GUILTY  Education
8  Under the Black Flag: The Romance and the Real...  Education
9            Where You'll Find Me: And Other Stories   Children

In [1]:
DESCRIBE books;

SyntaxError: invalid syntax (1385827788.py, line 1)

In [ ]:
import pandas as pd
from sqlalchemy import create_engine

engine = create_engine(
    "mysql+pymysql://root:ubmVuVNFzorFXnnexAwbdWqTdKnuTwcb@sakura.proxy.rlwy.net:29766/railway"
)

df = pd.read_sql("SHOW COLUMNS FROM books", engine)

print(df)

              Field          Type Null  Key Default           Extra
0           book_id           int   NO  PRI    None  auto_increment
1              isbn   varchar(20)  YES  UNI    None
2             title  varchar(500)  YES         None
3            author  varchar(255)  YES         None
4  publication_year           int  YES         None
5         publisher  varchar(255)  YES         None
6         image_url          text  YES         None
7          category   varchar(50)  YES         None

In [1]:
ALTER TABLE books
ADD COLUMN price DECIMAL(10,2) DEFAULT 499.00,
ADD COLUMN rent_price DECIMAL(10,2) DEFAULT 99.00,
ADD COLUMN stock INT DEFAULT 10;

SyntaxError: invalid syntax (1986339437.py, line 1)

In [ ]:
from sqlalchemy import create_engine, text

engine = create_engine(
    "mysql+pymysql://root:ubmVuVNFzorFXnnexAwbdWqTdKnuTwcb@sakura.proxy.rlwy.net:29766/railway"
)

with engine.begin() as conn:
    conn.execute(text("""
        ALTER TABLE books
        ADD COLUMN price DECIMAL(10,2) DEFAULT 499.00,
        ADD COLUMN rent_price DECIMAL(10,2) DEFAULT 99.00,
        ADD COLUMN stock INT DEFAULT 10;
    """))

print("Columns added successfully!")

Columns added successfully!

In [ ]:
from sqlalchemy import create_engine, text

engine = create_engine(
    "mysql+pymysql://root:ubmVuVNFzorFXnnexAwbdWqTdKnuTwcb@sakura.proxy.rlwy.net:29766/railway"
)

with engine.begin() as conn:
    conn.execute(text("""
        CREATE TABLE IF NOT EXISTS orders (
            order_id INT AUTO_INCREMENT PRIMARY KEY,
            isbn VARCHAR(20),
            title VARCHAR(500),
            customer_email VARCHAR(255),
            order_type VARCHAR(20),
            amount DECIMAL(10,2),
            order_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        );
    """))

print("Orders table created successfully!")

Orders table created successfully!

In [4]:
import pandas as pd
print(pd.read_sql("DESCRIBE orders", engine))

           Field          Type Null  Key            Default              Extra
0       order_id           int   NO  PRI                NaN     auto_increment
1        user_id           int   NO  MUL                NaN
2           isbn   varchar(20)   NO  MUL                NaN
3  customer_name  varchar(100)   NO                     NaN
4          phone   varchar(15)   NO                     NaN
5        address          text   NO                     NaN
6       quantity           int  YES                       1
7     order_date     timestamp  YES       CURRENT_TIMESTAMP  DEFAULT_GENERATED
8         status   varchar(30)  YES                 Pending

In [5]:
from sqlalchemy import text

with engine.begin() as conn:
    conn.execute(text("""
        DROP TABLE IF EXISTS orders;
    """))

print("Old orders table deleted.")

Old orders table deleted.

In [6]:
from sqlalchemy import text

with engine.begin() as conn:
    conn.execute(text("""
        CREATE TABLE orders (
            order_id INT AUTO_INCREMENT PRIMARY KEY,
            isbn VARCHAR(20),
            title VARCHAR(500),
            customer_email VARCHAR(255),
            order_type VARCHAR(20),
            amount DECIMAL(10,2),
            order_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        );
    """))

print("New orders table created.")

New orders table created.

In [7]:
pd.read_sql("DESCRIBE orders", engine)

,Field,Type,Null,Key,Default,Extra
0,order_id,int,NO,PRI,NaN,auto_increment
1,isbn,varchar(20),YES,,NaN,
2,title,varchar(500),YES,,NaN,
3,customer_email,varchar(255),YES,,NaN,
4,order_type,varchar(20),YES,,NaN,
5,amount,"decimal(10,2)",YES,,NaN,
6,order_date,timestamp,YES,,CURRENT_TIMESTAMP,DEFAULT_GENERATED

In [ ]:
from sqlalchemy import create_engine, text

engine = create_engine(
    "mysql+pymysql://root:ubmVuVNFzorFXnnexAwbdWqTdKnuTwcb@sakura.proxy.rlwy.net:29766/railway"
)

In [2]:
with engine.begin() as conn:
    conn.execute(text("DROP TABLE IF EXISTS orders"))

print("Old orders table dropped successfully.")

Old orders table dropped successfully.

In [3]:
with engine.begin() as conn:
    conn.execute(text("""
        CREATE TABLE orders (
            id INT AUTO_INCREMENT PRIMARY KEY,
            isbn VARCHAR(20) NOT NULL,
            title VARCHAR(255) NOT NULL,
            customer_name VARCHAR(100) NOT NULL,
            customer_email VARCHAR(100) NOT NULL,
            phone VARCHAR(20) NOT NULL,
            address TEXT NOT NULL,
            city VARCHAR(50) NOT NULL,
            pincode VARCHAR(10) NOT NULL,
            order_type ENUM('Buy','Rent') NOT NULL,
            amount DECIMAL(10,2) NOT NULL,
            order_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )
    """))

print("New orders table created successfully.")

New orders table created successfully.

In [4]:
import pandas as pd

df = pd.read_sql("SELECT * FROM orders", engine)
df

Empty DataFrame
Columns: [id, isbn, title, customer_name, customer_email, phone, address, city, pincode, order_type, amount, order_date]
Index: []

In [ ]:
from sqlalchemy import create_engine, text

engine = create_engine(
    "mysql+pymysql://root:ubmVuVNFzorFXnnexAwbdWqTdKnuTwcb@sakura.proxy.rlwy.net:29766/railway"

In [ ]:
from sqlalchemy import create_engine, text

engine = create_engine(
    "mysql+pymysql://root:ubmVuVNFzorFXnnexAwbdWqTdKnuTwcb@sakura.proxy.rlwy.net:29766/railway"
)

with engine.begin() as conn:

    conn.execute(text("DROP TABLE IF EXISTS admins"))

    conn.execute(text("""
        CREATE TABLE admins (
            id INT AUTO_INCREMENT PRIMARY KEY,
            username VARCHAR(50) UNIQUE NOT NULL,
            password VARCHAR(100) NOT NULL
        )
    """))

    conn.execute(text("""
        INSERT INTO admins (username, password)
        VALUES ('admin', 'admin123')
    """))

print("✅ Admin table created successfully.")

✅ Admin table created successfully.

In [4]:
import pandas as pd

df = pd.read_sql("SELECT * FROM admins", engine)
df

   id username  password
0   1    admin  admin123

In [ ]:
from sqlalchemy import create_engine, text

engine = create_engine(
    "mysql+pymysql://root:ubmVuVNFzorFXnnexAwbdWqTdKnuTwcb@sakura.proxy.rlwy.net:29766/railway"
)

with engine.begin() as conn:
    conn.execute(text("""
        ALTER TABLE orders
        ADD COLUMN rent_days INT DEFAULT NULL,
        ADD COLUMN return_date DATE DEFAULT NULL,
        ADD COLUMN status VARCHAR(20) DEFAULT 'Pending';
    """))

print("✅ Orders table updated successfully!")

✅ Orders table updated successfully!

In [2]:
import pandas as pd

df = pd.read_sql("DESCRIBE orders;", engine)
print(df)

             Field                Type Null  Key            Default  \
0               id                 int   NO  PRI                NaN
1             isbn         varchar(20)   NO                     NaN
2            title        varchar(255)   NO                     NaN
3    customer_name        varchar(100)   NO                     NaN
4   customer_email        varchar(100)   NO                     NaN
5            phone         varchar(20)   NO                     NaN
6          address                text   NO                     NaN
7             city         varchar(50)   NO                     NaN
8          pincode         varchar(10)   NO                     NaN
9       order_type  enum('Buy','Rent')   NO                     NaN
10          amount       decimal(10,2)   NO                     NaN
11      order_date           timestamp  YES       CURRENT_TIMESTAMP
12       rent_days                 int  YES                     NaN
13     return_date                date  YES                     NaN
14          status         varchar(20)  YES                 Pending

                Extra
0      auto_increment
1
2
3
4
5
6
7
8
9
10
11  DEFAULT_GENERATED
12
13
14

In [1]:
rent_orders = pd.read_sql(
    "SELECT COUNT(*) total FROM orders WHERE order_type='Rent'",
    engine
).iloc[0]["total"]

NameError: name 'pd' is not defined

In [2]:
import pandas as pd
from sqlalchemy import create_engine

In [1]:
engine = create_engine(
    "mysql://root:ubmVuVNFzorFXnnexAwbdWqTdKnuTwcb@sakura.proxy.rlwy.net:29766/railway"
)

NameError: name 'create_engine' is not defined

In [4]:
rent_orders = pd.read_sql(
    "SELECT COUNT(*) AS total FROM orders WHERE order_type='Rent'",
    engine
)

rent_orders

   total
0      0

In [5]:
import pandas as pd

df = pd.read_sql("SELECT * FROM books LIMIT 1", engine)

print(df.columns)

Index(['book_id', 'isbn', 'title', 'author', 'publication_year', 'publisher',
       'image_url', 'category', 'price', 'rent_price', 'stock'],
      dtype='str')

In [6]:
print(book)
print(book.index)

NameError: name 'book' is not defined

In [ ]:
import pandas as pd
from sqlalchemy import create_engine

engine = create_engine("mysql+pymysql://root:ubmVuVNFzorFXnnexAwbdWqTdKnuTwcb@sakura.proxy.rlwy.net:29766/railway")

isbn = "0399135782"   # Use the ISBN from your URL

df = pd.read_sql(
    "SELECT * FROM books WHERE isbn=%s",
    engine,
    params=(isbn,)
)

print(df)

if not df.empty:
    book = df.iloc[0]
    print(book)
    print(book.index)

   book_id        isbn                   title   author  publication_year  \
0        6  0399135782  The Kitchen God's Wife  Amy Tan              1991

          publisher                                          image_url  \
0  Putnam Pub Group  http://images.amazon.com/images/P/0399135782.0...

    category  price  rent_price  stock
0  Education  499.0        99.0     10
book_id                                                             6
isbn                                                       0399135782
title                                          The Kitchen God's Wife
author                                                        Amy Tan
publication_year                                                 1991
publisher                                            Putnam Pub Group
image_url           http://images.amazon.com/images/P/0399135782.0...
category                                                    Education
price                                                           499.0
rent_price                                                       99.0
stock                                                              10
Name: 0, dtype: object
Index(['book_id', 'isbn', 'title', 'author', 'publication_year', 'publisher',
       'image_url', 'category', 'price', 'rent_price', 'stock'],
      dtype='str')

In [8]:
pd.read_sql("DESCRIBE books", engine)

               Field           Type Null  Key Default           Extra
0            book_id            int   NO  PRI     NaN  auto_increment
1               isbn    varchar(20)  YES  UNI     NaN
2              title   varchar(500)  YES          NaN
3             author   varchar(255)  YES          NaN
4   publication_year            int  YES          NaN
5          publisher   varchar(255)  YES          NaN
6          image_url           text  YES          NaN
7           category    varchar(50)  YES          NaN
8              price  decimal(10,2)  YES       499.00
9         rent_price  decimal(10,2)  YES        99.00
10             stock            int  YES           10

In [9]:
pd.read_sql("DESCRIBE orders", engine)

,Field,Type,Null,Key,Default,Extra
0,id,int,NO,PRI,NaN,auto_increment
1,isbn,varchar(20),NO,,NaN,
2,title,varchar(255),NO,,NaN,
3,customer_name,varchar(100),NO,,NaN,
4,customer_email,varchar(100),NO,,NaN,
5,phone,varchar(20),NO,,NaN,
6,address,text,NO,,NaN,
7,city,varchar(50),NO,,NaN,
8,pincode,varchar(10),NO,,NaN,
9,order_type,"enum('Buy','Rent')",NO,,NaN,
10,amount,"decimal(10,2)",NO,,NaN,
11,order_date,timestamp,YES,,CURRENT_TIMESTAMP,DEFAULT_GENERATED
12,rent_days,int,YES,,NaN,
13,return_date,date,YES,,NaN,
14,status,varchar(20),YES,,Pending,

In [1]:
from sqlalchemy import text

with engine.begin() as conn:
    conn.execute(
        text("""
            ALTER TABLE books
            ADD COLUMN rent_days INT DEFAULT 7
        """)
    )

print("rent_days column added successfully!")

NameError: name 'engine' is not defined

In [ ]:
from sqlalchemy import create_engine

engine = create_engine( "mysql+pymysql://root:ubmVuVNFzorFXnnexAwbdWqTdKnuTwcb@sakura.proxy.rlwy.net:29766/railway"
)

In [3]:
from sqlalchemy import text

with engine.begin() as conn:
    conn.execute(
        text("""
            ALTER TABLE books
            ADD COLUMN rent_days INT DEFAULT 7
        """)
    )

print("rent_days column added successfully!")

rent_days column added successfully!

In [ ]:
import pandas as pd
from sqlalchemy import create_engine

engine = create_engine(
    "mysql+pymysql://root:ubmVuVNFzorFXnnexAwbdWqTdKnuTwcb@sakura.proxy.rlwy.net:29766/railway"
)

df = pd.read_sql("SELECT * FROM users", engine)
print(df)

   user_id        full_name                  email       phone   password  \
0        1  vaishnavi barve  vaishnavi25@gmail.com  1234567890  admin@123
1        2  viraj chaudhari      viraj13@gmail.com  9604675964   viraj123

           created_at
0 2026-07-10 20:31:28
1 2026-07-14 21:33:24

In [2]:
from sqlalchemy import create_engine

In [3]:
engine = create_engine(
    "mysql+pymysql://root:ubmVuVNFzorFXnnexAwbdWqTdKnuTwcb@sakura.proxy.rlwy.net:29766/railway"
)

In [4]:
from sqlalchemy import text

with engine.connect() as conn:
    print("Connected Successfully!")

Connected Successfully!