In [1]:
import pandas as pd
import numpy as np
from sqlalchemy import create_engine, text

In [19]:
engine = create_engine(
    "mysql+pymysql://root:%40pass123@localhost:3306/bookhub",
     pool_pre_ping=True
)

In [3]:
pd.read_sql("SELECT DATABASE();", engine)

  DATABASE()
0    bookhub

In [4]:
books = pd.read_csv(
    "../raw/Books.csv",
    encoding="latin-1",
    low_memory=False
)

books.shape

(271360, 8)

In [5]:
books.columns = [
    "isbn",
    "title",
    "author",
    "publication_year",
    "publisher",
    "image_url_s",
    "image_url_m",
    "image_url_l"
]

books.head()

,isbn,title,author,publication_year,publisher,image_url_s,image_url_m,image_url_l
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...

In [6]:
books = books[[
    "isbn",
    "title",
    "author",
    "publication_year",
    "publisher",
    "image_url_l"
]]

books.rename(columns={"image_url_l": "image_url"}, inplace=True)

books.head()

,isbn,title,author,publication_year,publisher,image_url
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...

In [7]:
books = books.drop_duplicates(subset=["isbn"])

books["publication_year"] = pd.to_numeric(
    books["publication_year"],
    errors="coerce"
)

books["publication_year"] = books["publication_year"].fillna(0).astype(int)

books = books.fillna("")

print(books.shape)
print(books["isbn"].duplicated().sum())

(271360, 6)
0

In [8]:
from sqlalchemy import text

with engine.begin() as conn:
    conn.execute(text("TRUNCATE TABLE books"))

print("Books table is empty.")

Books table is empty.

In [9]:
pd.read_sql("SELECT COUNT(*) AS total FROM books;", engine)

   total
0      0

In [11]:
books_small = books.head(5000).copy()

print(books_small.shape)

(5000, 6)

In [12]:
from sqlalchemy import text

with engine.begin() as conn:
    conn.execute(text("DROP TABLE IF EXISTS books"))

In [13]:
with engine.begin() as conn:
    conn.execute(text("""
    CREATE TABLE books (
        book_id INT AUTO_INCREMENT PRIMARY KEY,
        isbn VARCHAR(20) UNIQUE,
        title VARCHAR(500),
        author VARCHAR(255),
        publication_year INT,
        publisher VARCHAR(255),
        image_url TEXT
    );
    """))

In [14]:
books_small.to_sql(
    "books",
    con=engine,
    if_exists="append",
    index=False
)

print("5000 books imported successfully!")

5000 books imported successfully!

In [15]:
pd.read_sql("SELECT COUNT(*) AS total FROM books;", engine)

   total
0   5000

In [16]:
import pandas as pd

pd.read_sql("SELECT COUNT(*) AS total FROM books;", engine)

   total
0   5000

In [17]:
pd.read_sql("SELECT * FROM books LIMIT 5;", engine)

,book_id,isbn,title,author,publication_year,publisher,image_url
0,1,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...
1,2,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...
2,3,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...
3,4,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...
4,5,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...